CREATE TABLE bid (
  P_ID NUMBER PRIMARY KEY,
  P_CATEGORY1 varchar2(100),
  P_NAME varchar2(100),
  P_PRICE NUMBER,
  P_MADEN varchar2(100),
  P_BRAND varchar2(100),
  P_MODEL varchar2(100),
  P_MAXBUY NUMBER,
  P_ETC varchar2(100),
  P_SEARCH varchar2(100),
  P_VALIDATION varchar2(100),
  P_T_TYPE varchar2(100),
  P_T_P_TYPE varchar2(100),
  P_B_IMG_SRC varchar2(100),
  P_S_IMG_SRC varchar2(100),
  P_DETAIL varchar2(1000),
  P_CATEGORY2 varchar2(100),
  P_DATE DATE,
  USERS varchar2(100),
  COUNTS NUMBER,
  P_ENDDATE DATE,
  T_USER varchar2(45)
);

SELECT * FROM BID

CREATE SEQUENCE BID_P_ID MINVALUE 0 START WITH 1;

INSERT INTO bid (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS,P_ENDDATE,T_USER) VALUES (17, 'CLASS1', 'PRODUCT1', 1000, 'DEFAULT', 'DEFAULT', 'DEFAULT', 30, 'DEFAULT', 'DS ONE 슈퍼카드 SDHC 컴퓨터', '6', 'DEFAULT', 'DEFAULT', '200711191130659994.jpg', '200711191130659994.jpg', 'DEFAULT', 'DEFAULT', SYSDATE, 'srzero', 0, SYSDATE, NULL);

INSERT INTO bid (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS,P_ENDDATE,T_USER) VALUES (18, 'CLASS1', 'PRODUCT2', 1500, 'DEFAULT', 'DEFAULT', 'DEFAULT', 50, 'DEFAULT', 'NDSL용 터치팬', '3', 'DEFAULT', 'DEFAULT', '123213123.jpg', '123213123.jpg', 'DEFAULT', 'DEFAULT', SYSDATE, 'srzero', 0, SYSDATE, 'srzero');

INSERT INTO bid (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS,P_ENDDATE,T_USER) VALUES (19, 'CLASS1', 'PRODUCT3', 6000, 'DEFAULT', 'DEFAULT', 'DEFAULT', 10, 'DEFAULT', 'HP K550 CANNON', '20', 'DEFAULT', 'DEFAULT', 'img_sub01_01.gif', 'img_sub01_01.gif', 'DEFAULT', 'DEFAULT', SYSDATE, 'srzero', 0, SYSDATE, 'hoping');

INSERT INTO bid (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS,P_ENDDATE,T_USER) VALUES (20, 'CLASS1', 'PRODUCT4', 100000, 'DEFAULT', 'DEFAULT', 'DEFAULT', 30, 'DEFAULT', 'mp3 pmp pdp pda', '50', 'DEFAULT', 'DEFAULT', 'MP3.jpg', 'MP3.jpg', 'DEFAULT', 'DEFAULT', SYSDATE, 'srzero', 0, SYSDATE, NULL);


/***********************************************************************/
CREATE TABLE buy (
  id NUMBER PRIMARY KEY,
  USERID VARCHAR2(45),
  PRODUCTID NUMBER,
  JUMUN_MANY NUMBER,
  TOTALMONEY NUMBER
);

CREATE SEQUENCE BUY_ID MINVALUE 0 START WITH 1;

INSERT INTO buy (id,USERID,PRODUCTID,JUMUN_MANY,TOTALMONEY) VALUES (34, 'srzero', 4, 1, 1340000);

INSERT INTO buy (id,USERID,PRODUCTID,JUMUN_MANY,TOTALMONEY) VALUES (35, 'srzero', 5, 1, 1000000);

INSERT INTO buy (id,USERID,PRODUCTID,JUMUN_MANY,TOTALMONEY) VALUES (36, 'srzero', 5, 1, 1000000);

SELECT * FROM BUY

/***********************************************************************/
CREATE TABLE cart (
  id NUMBER PRIMARY KEY,
  USERID VARCHAR2(30),
  PRODUCTID NUMBER,
  JUMUN_MANY NUMBER,
  TOTALMONEY NUMBER
);

CREATE SEQUENCE CART_ID MINVALUE 0 START WITH 1;

INSERT INTO cart (id,USERID,PRODUCTID,JUMUN_MANY,TOTALMONEY) VALUES (1, 'srzero', 10, 1, 200000);

SELECT * FROM CART

/***********************************************************************/
CREATE TABLE muser (
  ID NUMBER PRIMARY KEY,
  M_ID VARCHAR2(20),
  M_NAME VARCHAR2(20),
  M_JUMIN VARCHAR2(20),
  M_PASSWORD VARCHAR2(20),
  M_ADDRESS VARCHAR2(100),
  M_TYPE NUMBER
);

CREATE SEQUENCE MUSER_ID MINVALUE 0 START WITH 1;

INSERT INTO muser (ID,M_ID,M_NAME,M_JUMIN,M_PASSWORD,M_ADDRESS,M_TYPE) VALUES (4,'srzero','DEFAULT','830920-1913117','1234','DEFAULT',0);

INSERT INTO muser (ID,M_ID,M_NAME,M_JUMIN,M_PASSWORD,M_ADDRESS,M_TYPE) VALUES (5,'hoping','DEFAULT','830415-1148515','1234','DEFAULT',1);

SELECT * FROM MUSER

/***********************************************************************/
CREATE TABLE product (
  P_ID NUMBER PRIMARY KEY,
  P_CATEGORY1 VARCHAR2(45),
  P_NAME VARCHAR2(45),
  P_PRICE NUMBER,
  P_MADEN VARCHAR2(45),
  P_BRAND VARCHAR2(45),
  P_MODEL VARCHAR2(45),
  P_MAXBUY NUMBER,
  P_ETC VARCHAR2(45),
  P_SEARCH VARCHAR2(45),
  P_VALIDATION VARCHAR2(45),
  P_T_TYPE VARCHAR2(45),
  P_T_P_TYPE VARCHAR2(45),
  P_B_IMG_SRC VARCHAR2(45),
  P_S_IMG_SRC VARCHAR2(45),
  P_DETAIL VARCHAR2(1000),
  P_CATEGORY2 VARCHAR2(45),
  P_DATE DATE,
  USERS VARCHAR2(45),
  COUNTS NUMBER
  );

  CREATE SEQUENCE PRODUCT_P_ID MINVALUE 0 START WITH 1;
  
INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (2,'CLASS1','PRODUCT2',1199000,'DEFAULT','DEFAULT','DEFAULT',500,'DEFAULT','SEACH1','20','DEFAULT','DEFAULT','RIPPLEN7500_0.jpg','RIPPLEN7500_0.jpg','DEFAULT','DEFAULT',SYSDATE,'srzero',NULL);

INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (3,'CLASS1','PRODUCT3',1260000,'DEFAULT','DEFAULT','DEFAULT',497,'DEFAULT','SEACH2','30','DEFAULT','DEFAULT','NTX60W183_0.jpg','NTX60W183_0.jpg','DEFAULT','DEFAULT',SYSDATE,'srzero',2);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (4,'CLASS1','PRODUCT4',1340000,'DEFAULT','DEFAULT','DEFAULT',495,'DEFAULT','SEACH3','60','DEFAULT','DEFAULT','NTX1C120A_2.jpg','NTX1C120A_2.jpg','DEFAULT','DEFAULT',SYSDATE,'srzero',6);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (5,'CLASS2','PRODUCT5',1000000,'DEFAULT','DEFAULT','DEFAULT',495,'DEFAULT','SEACH4','10','DEFAULT','DEFAULT','NTX06M160_0.jpg','NTX06M160_0.jpg','DEFAULT','DEFAULT',SYSDATE,'srzero',3);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (6,'CLASS2','PRODUCT6',586000,'DEFAULT','DEFAULT','DEFAULT',389,'DEFAULT','SEACH5','100','DEFAULT','DEFAULT','220721_1.jpg','220721_1.jpg','DEFAULT','DEFAULT',SYSDATE,'srzero',4);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (7,'CLASS2','PRODUCT7',8800,'DEFAULT','DEFAULT','DEFAULT',500,'DEFAULT','SEACH6',NULL,'DEFAULT','DEFAULT','book1.jpg','book1.jpg','DEFAULT','DEFAULT',SYSDATE,'hoping',0);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (8,'CLASS3','PRODUCT8',12500,'DEFAULT','DEFAULT','DEFAULT',500,'DEFAULT','SEACH7',NULL,'DEFAULT','DEFAULT','music1.jpg','music1.jpg','DEFAULT','DEFAULT',SYSDATE,'hoping',0);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (9,'CLASS3','PRODUCT9',111000,'DEFAULT','DEFAULT','DEFAULT',300,'DEFAULT','SEACH8',NULL,'DEFAULT','DEFAULT','DVD1.jpg','DVD1.jpg','DEFAULT','DEFAULT',SYSDATE,'hoping',0);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (10,'CLASS3','PRODUCT10',200000,'DEFAULT','DEFAULT','DEFAULT',499,'DEFAULT','SEACH9',NULL,'DEFAULT','DEFAULT','LCD.jpg','LCD.jpg','DEFAULT','DEFAULT',SYSDATE,'hoping',0);	INSERT INTO product (P_ID,P_CATEGORY1,P_NAME,P_PRICE,P_MADEN,P_BRAND,P_MODEL,P_MAXBUY,P_ETC,P_SEARCH,P_VALIDATION,P_T_TYPE,P_T_P_TYPE,P_B_IMG_SRC,P_S_IMG_SRC,P_DETAIL,P_CATEGORY2,P_DATE,USERS,COUNTS) VALUES (11,'CLASS3','PRODUCT11',192000,'DEFAULT','DEFAULT','DEFAULT',30,'DEFAULT','SEACH10','30','DEFAULT','DEFAULT','nintendo_300.gif','nintendo_100.gif','DEFAULT','DEFAULT',SYSDATE,'srzero',0);

SELECT * FROM PRODUCT
  /***********************************************************************/
  